import type { PineDay, PineDayConfig } from './pine-types';

export const PINE_DAY_CONFIG: Record<PineDay, PineDayConfig> = {
  1: {
    day: 1,
    stage: 'Grounding & Anchoring',
    title: 'Planting the Seed',
    emotionalIntent: 'Planting a purpose or intention.',
    instruction: 'Rest your finger on the seed, then press it gently into the soil.',
    contemplation: 'What intention are you ready to place in the soil?',
    gesture: 'press-hold',
    image: '../assets/day-01-rooting-the-seed.webp',
    light: 'sunrise',
    material: 'soil',
    haptic: 'anchorage',
    accessibilityInstruction: 'Use the guided press-into-soil control until the seed feels seated.',
  },
  2: {
    day: 2,
    stage: 'Grounding & Anchoring',
    title: 'Deep Anchor',
    emotionalIntent: 'Building foundational strength.',
    instruction: 'Draw one unhurried line down the taproot’s path.',
    contemplation: 'Strength begins below the surface.',
    gesture: 'downward-drag',
    image: '../assets/day-02-deep-anchor.webp',
    light: 'sunrise',
    material: 'root',
    haptic: 'anchorage',
    accessibilityInstruction: 'Use the downward progress control until the root reaches the deep soil.',
  },
  3: {
    day: 3,
    stage: 'Grounding & Anchoring',
    title: 'First Light',
    emotionalIntent: 'Celebrating the first signs of visible progress.',
    instruction: 'Brush loose soil slowly away from around the young seedling. Every cleared pass stays open.',
    contemplation: 'A first green sign is enough.',
    gesture: 'soft-brush',
    image: '../assets/day-03-seedling-reveal.png',
    light: 'sunrise',
    material: 'shoot',
    haptic: 'fibre',
    accessibilityInstruction: 'Use the gentle brush control to clear soil around the single young seedling in calm, lasting passes.',
  },
  4: {
    day: 4,
    stage: 'Structuring & Stretching',
    title: 'Developing Trunk',
    emotionalIntent: 'Reinforcing personal structure and integrity.',
    instruction: 'Trace steadily upward along the forming trunk.',
    contemplation: 'Let your structure rise from what is grounded.',
    gesture: 'upward-trace',
    image: '../assets/day-04-developing-trunk.webp',
    light: 'daylight',
    material: 'bark',
    haptic: 'fibre',
    accessibilityInstruction: 'Use the upright trace control and move it slowly toward the crown.',
  },
  5: {
    day: 5,
    stage: 'Structuring & Stretching',
    title: 'Stronger Structure',
    emotionalIntent: 'Cultivating flexible strength.',
    instruction: 'Begin at the gold point. Spiral slowly upward around the young trunk.',
    contemplation: 'Layer by layer, the young trunk finds its strength.',
    gesture: 'spiral-up',
    image: '../assets/day-05-stronger-structure.webp',
    light: 'daylight',
    material: 'branch',
    haptic: 'fibre',
    accessibilityInstruction: 'Use the upward spiral control from the gold base point until the young trunk has been strengthened.',
  },
  6: {
    day: 6,
    stage: 'Structuring & Stretching',
    title: 'Branching Out',
    emotionalIntent: 'Embracing growth and expansion.',
    instruction: 'Touch a branch, then sweep outward along the branch you chose.',
    contemplation: 'There is room to extend.',
    gesture: 'outward-sweep',
    image: '../assets/day-06-branching-out.webp',
    light: 'daylight',
    material: 'canopy',
    haptic: 'fibre',
    accessibilityInstruction: 'Use the branch trace control to follow each visible branch you choose.',
  },
  7: {
    day: 7,
    stage: 'Weathering & Completing',
    title: 'Weathering Growth',
    emotionalIntent: 'Mastering resilience.',
    instruction: 'Brush slowly left and right across the canopy. Watch the tree bend with the wind, then return.',
    contemplation: 'Flexibility keeps the roots intact.',
    gesture: 'wind-brush',
    image: '../assets/day-07-weathering-growth.webp',
    light: 'mist',
    material: 'canopy',
    haptic: 'air',
    accessibilityInstruction: 'Use the wind response control to guide a gentle sway.',
  },
  8: {
    day: 8,
    stage: 'Weathering & Completing',
    title: 'Forming Features',
    emotionalIntent: 'Integrating wisdom and complexity.',
    instruction: 'Touch five warm points of sap or young cones. Each touch will reveal a quiet glow.',
    contemplation: 'Detail holds a living history.',
    gesture: 'feature-touch',
    image: '../assets/day-08-forming-features.webp',
    light: 'mist',
    material: 'bark',
    haptic: 'air',
    accessibilityInstruction: 'Use the feature discovery control to notice each small detail.',
  },
  9: {
    day: 9,
    stage: 'Weathering & Completing',
    title: 'Full Maturity',
    emotionalIntent: 'Completed growth, peace, and deep rootedness.',
    instruction: 'Sweep outward from the trunk to reveal the tree’s wider forest landscape.',
    contemplation: 'You are rooted, complete, and still becoming.',
    gesture: 'landscape-release',
    image: '../assets/day-09-full-maturity.webp',
    light: 'mist',
    material: 'forest',
    haptic: 'release',
    accessibilityInstruction: 'Use the landscape release control to open the wider view.',
  },
};

export function getPineDayConfig(day: PineDay): PineDayConfig {
  return PINE_DAY_CONFIG[day];
}
