import type { PineDay, PineDayConfig } from './pine-types';

export const PINE_DAY_CONFIG: Record<PineDay, PineDayConfig> = {
  1: {
    day: 1,
    stage: 'Grounding & Anchoring',
    title: 'Rooting the Seed',
    emotionalIntent: 'Planting a purpose or intention.',
    instruction: 'Rest your finger on the seed, then press slowly until the soil yields.',
    contemplation: 'What is ready to take root, quietly and without force?',
    gesture: 'press-hold',
    image: '../assets/day-01-rooting-the-seed.webp',
    light: 'sunrise',
    material: 'soil',
    haptic: 'anchorage',
    accessibilityInstruction: 'Use the guided hold control and keep it pressed until it completes.',
  },
  2: {
    day: 2,
    stage: 'Grounding & Anchoring',
    title: 'Deep Anchor',
    emotionalIntent: 'Building foundational strength.',
    instruction: 'Draw one unhurried line down the taproot’s path.',
    contemplation: 'Strength begins below the surface.',
    gesture: 'downward-drag',
    image: '../assets/day-02-deep-anchor.webp',
    light: 'sunrise',
    material: 'root',
    haptic: 'anchorage',
    accessibilityInstruction: 'Use the downward progress control until the root reaches the deep soil.',
  },
  3: {
    day: 3,
    stage: 'Grounding & Anchoring',
    title: 'First Light',
    emotionalIntent: 'Celebrating the first signs of visible progress.',
    instruction: 'Brush loose soil softly away from the new needles.',
    contemplation: 'A first green sign is enough.',
    gesture: 'soft-brush',
    image: '../assets/day-03-first-light.webp',
    light: 'sunrise',
    material: 'shoot',
    haptic: 'fibre',
    accessibilityInstruction: 'Use the gentle brush control to clear the soil in calm passes.',
  },
  4: {
    day: 4,
    stage: 'Structuring & Stretching',
    title: 'Developing Trunk',
    emotionalIntent: 'Reinforcing personal structure and integrity.',
    instruction: 'Trace steadily upward along the forming trunk.',
    contemplation: 'Let your structure rise from what is grounded.',
    gesture: 'upward-trace',
    image: '../assets/day-04-developing-trunk.webp',
    light: 'daylight',
    material: 'bark',
    haptic: 'fibre',
    accessibilityInstruction: 'Use the upright trace control and move it slowly toward the crown.',
  },
  5: {
    day: 5,
    stage: 'Structuring & Stretching',
    title: 'Stronger Structure',
    emotionalIntent: 'Cultivating flexible strength.',
    instruction: 'Pinch to notice the whorls, then circle once to strengthen them.',
    contemplation: 'Strength can remain responsive.',
    gesture: 'pinch-circle',
    image: '../assets/day-05-stronger-structure.webp',
    light: 'daylight',
    material: 'branch',
    haptic: 'fibre',
    accessibilityInstruction: 'Use the strengthening circle control until the whorl settles.',
  },
  6: {
    day: 6,
    stage: 'Structuring & Stretching',
    title: 'Branching Out',
    emotionalIntent: 'Embracing growth and expansion.',
    instruction: 'Sweep outward along the branches toward the light.',
    contemplation: 'There is room to extend.',
    gesture: 'outward-sweep',
    image: '../assets/day-06-branching-out.webp',
    light: 'daylight',
    material: 'canopy',
    haptic: 'fibre',
    accessibilityInstruction: 'Use the outward sweep control to extend the branch response.',
  },
  7: {
    day: 7,
    stage: 'Weathering & Completing',
    title: 'Weathering Growth',
    emotionalIntent: 'Mastering resilience.',
    instruction: 'Move with the canopy slowly, letting it bend and return.',
    contemplation: 'Flexibility keeps the roots intact.',
    gesture: 'wind-brush',
    image: '../assets/day-07-weathering-growth.webp',
    light: 'mist',
    material: 'canopy',
    haptic: 'air',
    accessibilityInstruction: 'Use the wind response control to guide a gentle sway.',
  },
  8: {
    day: 8,
    stage: 'Weathering & Completing',
    title: 'Forming Features',
    emotionalIntent: 'Integrating wisdom and complexity.',
    instruction: 'Notice the sap and young cones with individual, unhurried touches.',
    contemplation: 'Detail holds a living history.',
    gesture: 'feature-touch',
    image: '../assets/day-08-forming-features.webp',
    light: 'mist',
    material: 'bark',
    haptic: 'air',
    accessibilityInstruction: 'Use the feature discovery control to notice each small detail.',
  },
  9: {
    day: 9,
    stage: 'Weathering & Completing',
    title: 'Full Maturity',
    emotionalIntent: 'Completed growth, peace, and deep rootedness.',
    instruction: 'Sweep outward to open the tree into its wider landscape.',
    contemplation: 'You are rooted, complete, and still becoming.',
    gesture: 'landscape-release',
    image: '../assets/day-09-full-maturity.webp',
    light: 'mist',
    material: 'forest',
    haptic: 'release',
    accessibilityInstruction: 'Use the landscape release control to open the wider view.',
  },
};

export function getPineDayConfig(day: PineDay): PineDayConfig {
  return PINE_DAY_CONFIG[day];
}
